version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: b2b
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - b2b_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: b2b-backend
    command: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/b2b
      PYTHONUNBUFFERED: 1
    networks:
      - b2b_network

volumes:
  postgres_data:

networks:
  b2b_network:
    driver: bridge
