version: '3.8'

services:
  db:
    image: postgres:15
    container_name: b2b_db_1
    environment:
      POSTGRES_USER: b2b_user
      POSTGRES_PASSWORD: b2b_pass
      POSTGRES_DB: b2b_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - b2b_network
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: b2b-backend
    command: bash -c "/wait-for-db.sh db && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - SCRAPER_API_KEY=${SCRAPER_API_KEY}
    depends_on:
      - db
    networks:
      - b2b_network

volumes:
  postgres_data:

networks:
  b2b_network:
    driver: bridge
