version: '3.8'

services:
  db:
    image: postgres:15
    container_name: b2b_db_1
    environment:
      POSTGRES_USER: b2b_user
      POSTGRES_PASSWORD: b2b_pass
      POSTGRES_DB: b2b_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - b2b_network
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: b2b-backend
    command: bash -c "chmod +x /app/wait-for-db.sh && /app/wait-for-db.sh db && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug"
    volumes:
      - ./backend:/app
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://b2b_user:b2b_pass@db:5432/b2b_db
      POSTGRES_USER: b2b_user
      POSTGRES_PASSWORD: b2b_pass
      POSTGRES_DB: b2b_db
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
    networks:
      - b2b_network
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  b2b_network:
    driver: bridge
